import { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'en' | 'urdu'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Language switcher
    'language': 'Language',
    'english': 'English',
    'urdu': 'Urdu',
    
    // Module names
    'connect': 'Connect',
    'parenting_in_pandemic': 'Parenting in Pandemic',
    'family_rules': 'Family Rules',
    'nurture': 'Nurture',
    'conflict': 'Conflict',
    'friends': 'Friends',
    'health_habits': 'Health Habits',
    'problems': 'Problems',
    'anxiety': 'Anxiety',
    'seeking_help': 'Seeking Help',
    
    // Navigation
    'home': 'Home',
    'resources': 'Resources',
    'contact_us': 'Contact Us',
    'sign_in': 'Sign In',
    'sign_out': 'Sign Out',
    'get_started': 'Get Started',
    'my_profile': 'My Profile',
    'dashboard': 'Dashboard',
    'admin_dashboard': 'Admin Dashboard',
    'continue_journey': 'Continue Your Journey',
    'start_journey': 'Start Your Journey',
    'back_to_home': 'Back to Home',
    
    // Home page - Hero
    'trusted_by_parents': 'Trusted by 10,000+ Parents Worldwide',
    'partners_in': 'Partners in',
    'parenting_title': 'Parenting',
    'hero_description': 'Empowering families with evidence-based strategies, practical tools, and expert guidance to build stronger, healthier relationships.',
    'go_to_dashboard': 'Go to Dashboard',
    'happy_families': 'Happy Families',
    'expert_modules': 'Expert Modules',
    'success_rate': 'Success Rate',
    
    // Home page - Features
    'why_choose': 'Why Choose Partners in Parenting?',
    'comprehensive_support': 'Comprehensive support designed to help your family thrive at every stage.',
    'strengthen_relationships': 'Strengthen Relationships',
    'strengthen_desc': 'Build stronger bonds with your children through evidence-based parenting strategies.',
    'expert_guidance': 'Expert Guidance',
    'expert_desc': 'Access professional advice and practical tools from child development specialists.',
    'learn_at_pace': 'Learn at Your Pace',
    'learn_desc': 'Self-paced modules designed to fit into your busy parenting schedule.',
    'proven_methods': 'Proven Methods',
    'proven_desc': 'Techniques backed by research to help your family thrive.',
    
    // Home page - How it works
    'how_it_works': 'How It Works',
    'simple_steps': 'Simple steps to transform your parenting journey.',
    'step1_title': 'Complete Assessments',
    'step1_desc': 'Take our comprehensive parenting assessments to understand your strengths and areas for growth.',
    'step2_title': 'Access Modules',
    'step2_desc': 'Explore personalized learning modules designed specifically for your family\'s needs.',
    'step3_title': 'Transform Family Life',
    'step3_desc': 'Apply proven strategies and watch your family relationships flourish.',
    
    // Home page - Benefits
    'what_you_gain': 'What You\'ll Gain',
    'program_provides': 'Our program provides you with practical tools and knowledge to create a nurturing family environment.',
    'benefit1': 'Improved communication with your children',
    'benefit2': 'Effective discipline strategies',
    'benefit3': 'Stress management techniques',
    'benefit4': 'Better understanding of child development',
    'benefit5': 'Stronger family bonds',
    'benefit6': 'Confidence in your parenting decisions',
    'core_assessments': 'Core Assessments',
    'learning_modules': 'Learning Modules',
    'resource_access': 'Resource Access',
    'satisfaction': 'Satisfaction',
    
    // Home page - CTA
    'ready_to_transform': 'Ready to Transform Your Parenting Journey?',
    'join_parents': 'Join thousands of parents who have already discovered the power of evidence-based parenting strategies.',
    'get_started_free': 'Get Started Free',
    'learn_more': 'Learn More',
    
    // Footer
    'empowering_families': 'Empowering families with evidence-based strategies and expert guidance since 2024.',
    'quick_links': 'Quick Links',
    'account': 'Account',
    'all_rights_reserved': 'All rights reserved.',
    
    // Landing page
    'welcome_back': 'Welcome back',
    'my_dashboard': 'My Dashboard',
    'continue_modules': 'Continue to Modules',
    'complete_assessment': 'Complete Assessment',
    'welcome_get_started': 'Welcome! Let\'s Get Started',
    'assessment_desc': 'Before accessing modules, please complete our initial assessment to help us provide you with most relevant content and support.',
    'comprehensive_modules': '10 Comprehensive Modules',
    'modules_desc': 'From building connections to managing anxiety, each module provides practical strategies for common parenting challenges.',
    'interactive_activities': 'Interactive Activities',
    'activities_desc': 'Engage with quizzes, reflective exercises, and practical activities designed to reinforce learning.',
    'personalized_support': 'Personalized Support',
    'support_desc': 'Our assessment tools help tailor the content to your specific family needs and challenges.',
    'available_modules': 'Available Modules',
    'program_desc': 'A comprehensive parenting support program designed to help families thrive.',
    
    // Dashboard
    'user_dashboard': 'User Dashboard',
    'overview': 'Overview',
    'my_scales': 'My Scales',
    'module_progress': 'Module Progress',
    'scales_completed': 'Scales Completed',
    'modules_completed': 'Modules Completed',
    'average_score': 'Average Score',
    'time_spent': 'Time Spent',
    'redo_assessment': 'Redo Assessment',
    'view_modules': 'View Modules',
    'no_modules': 'No modules available',
    'recent_scale_results': 'Recent Scale Results',
    'score': 'Score',
    'no_scales_completed': 'No scales completed yet',
    'no_modules_enrolled': 'No modules enrolled yet',
    'quick_actions': 'Quick Actions',
    'review_scales': 'Review Scales',
    'view_assessments': 'View assessments',
    'continue_learning': 'Continue Learning',
    'access_modules': 'Access modules',
    'view_profile': 'View Profile',
    'manage_account': 'Manage account',
    'my_scale_responses': 'My Scale Responses',
    'scale_name': 'Scale Name',
    'risk_level': 'Risk Level',
    'completed_date': 'Completed',
    'time_taken': 'Time Taken',
    'actions': 'Actions',
    'redo': 'Redo',
    'no_scale_responses': 'No scale responses found. Take your first assessment to get started!',
    'my_module_progress': 'My Module Progress',
    'module_name': 'Module Name',
    'progress_col': 'Progress',
    'status_col': 'Status',
    'last_accessed': 'Last Accessed',
    'action': 'Action',
    'review': 'Review',
    'continue_btn': 'Continue',
    'no_module_enrollments': 'No module enrollments found. Visit any module page to start learning!',
    'enrolled': 'Enrolled',
    'complete_percent': 'complete',
    
    // Profile page
    'manage_account_settings': 'Manage your account settings and view your progress',
    'profile_updated': 'Profile updated successfully!',
    'failed_update_profile': 'Failed to update profile',
    'passwords_not_match': 'New passwords do not match',
    'password_changed': 'Password changed successfully!',
    'failed_change_password': 'Failed to change password',
    'personal_information': 'Personal Information',
    'saving': 'Saving...',
    'full_name': 'Full Name',
    'phone': 'Phone',
    'location': 'Location',
    'member_since': 'Member Since',
    'bio': 'Bio',
    'phone_placeholder': '+1 (555) 000-0000',
    'bio_placeholder': 'Tell us about yourself...',
    'not_provided': 'Not provided',
    'no_bio': 'No bio provided yet.',
    'security': 'Security',
    'change_password_desc': 'Change your account password',
    'change': 'Change',
    'view_dashboard': 'View Dashboard',
    'my_assessments': 'My Assessments',
    'your_progress': 'Your Progress',
    'modules_done': 'Modules Done',
    'avg_score': 'Avg Score',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_new_password': 'Confirm New Password',
    'changing': 'Changing...',
    
    // Auth pages
    'sign_in_to_account': 'Sign in to your account',
    'create_new_account': 'create a new account',
    'enter_email': 'Enter your email',
    'enter_password': 'Enter your password',
    'signing_in': 'Signing in...',
    'sign_in_btn': 'Sign in',
    'login_failed': 'Login failed. Please try again.',
    'create_your_account': 'Create your account',
    'sign_in_existing': 'sign in to your existing account',
    'enter_full_name': 'Enter your full name',
    'confirm_password': 'Confirm Password',
    'passwords_not_match_auth': 'Passwords do not match',
    'password_min_chars': 'Password must be at least 6 characters long',
    'creating_account': 'Creating account...',
    'create_account_btn': 'Create account',
    'registration_failed': 'Registration failed. Please try again.',
    
    // Contact page
    'contact_hero_desc': 'We\'d love to hear from you. Get in touch with our team for any questions or support.',
    'office': 'Office',
    'working_hours': 'Working Hours',
    'mon_fri_hours': 'Mon-Fri from 8am to 5pm',
    'respond_24h': 'We respond within 24 hours',
    'send_message': 'Send us a Message',
    'your_name': 'Your Name',
    'email_address': 'Email Address',
    'subject': 'Subject',
    'select_subject': 'Select a subject',
    'general_inquiry': 'General Inquiry',
    'technical_support': 'Technical Support',
    'billing_question': 'Billing Question',
    'feedback': 'Feedback',
    'other': 'Other',
    'message': 'Message',
    'how_can_help': 'How can we help you?',
    'send_message_btn': 'Send Message',
    'message_sent': 'Message Sent!',
    'get_back_24h': 'We\'ll get back to you within 24 hours.',
    'faq': 'Frequently Asked Questions',
    'still_have_questions': 'Still have questions?',
    'support_team_help': 'Our support team is always here to help you with any questions or concerns.',
    'email_support_team': 'Email Support Team',
    'map_coming_soon': 'Interactive Map Coming Soon',
    'faq_q1': 'How do I get started with the program?',
    'faq_a1': 'Simply create an account, complete the initial assessments, and you\'ll be guided through personalized learning modules.',
    'faq_q2': 'Is the program suitable for all parenting stages?',
    'faq_a2': 'Yes! Our program is designed to support parents with children of all ages, from toddlers to teenagers.',
    'faq_q3': 'Can I access the program on mobile devices?',
    'faq_a3': 'Absolutely! Our platform is fully responsive and works seamlessly on smartphones, tablets, and computers.',
    'faq_q4': 'What if I need additional support?',
    'faq_a4': 'We offer various support channels including email support, community forums, and optional one-on-one consultations.',
    
    // Scales
    'scale_child_mental_health': 'Child Mental Health Scale',
    'scale_parent_child_relationship': 'Parent-Child Relationship Scale',
    'scale_parental_mental_wellbeing': 'Parental Mental Wellbeing Scale',
    'scale_parental_self_efficacy': 'Parental Self-Efficacy Scale',
    'question': 'Question',
    'of': 'of',
    'next': 'Next',
    'previous': 'Previous',
    'submit': 'Submit',
    'retake': 'Retake',
    'your_score': 'Your Score',
    'completed': 'Completed',
    'in_progress': 'In Progress',
    'not_started': 'Not Started',
    
    // Common
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'cancel': 'Cancel',
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'confirm': 'Confirm',
    'close': 'Close',
    'back': 'Back',
    'continue': 'Continue',
    'welcome': 'Welcome',
    'supporting_families': 'Supporting families together',
    'progress': 'Progress',
    'completed_percent': 'completed',
  },
  urdu: {
    // Language switcher
    'language': 'زبان',
    'english': 'انگریزی',
    'urdu': 'اردو',
    
    // Module names
    'connect': 'جڑنا',
    'parenting_in_pandemic': 'وبا میں پرورش',
    'family_rules': 'خانہ داری کے قواعد',
    'nurture': 'پرورش',
    'conflict': 'تصادم',
    'friends': 'دوست',
    'health_habits': 'صحت کی عادات',
    'problems': 'مسائل',
    'anxiety': 'فکر',
    'seeking_help': 'مدد حاصل کرنا',
    
    // Navigation
    'home': 'ہوم',
    'resources': 'وسائل',
    'contact_us': 'ہم سے رابطہ کریں',
    'sign_in': 'سائن ان کریں',
    'sign_out': 'سائن آؤٹ کریں',
    'get_started': 'شروع کریں',
    'my_profile': 'میری پروفائل',
    'dashboard': 'ڈیش بورڈ',
    'admin_dashboard': 'ایڈمن ڈیش بورڈ',
    'continue_journey': 'اپنے سفر کو جاری رکھیں',
    'start_journey': 'اپنا سفر شروع کریں',
    'back_to_home': 'ہوم پر واپس جائیں',
    
    // Home page - Hero
    'trusted_by_parents': 'دنیا بھر سے 10,000+ والدین کا اعتماد',
    'partners_in': 'شراکت دار',
    'parenting_title': 'پرورش میں',
    'hero_description': 'مزید مضبوط، صحت مند تعلقات بنانے کے لیے ثبوت پر مبنی حکمت عملی، عملی ٹولز اور ماہر رہنمائی کے ساتھ خاندانوں کو بااختیار بنانا۔',
    'go_to_dashboard': 'ڈیش بورڈ پر جائیں',
    'happy_families': 'خوش خاندان',
    'expert_modules': 'ماہر ماڈیولز',
    'success_rate': 'کامیابی کی شرح',
    
    // Home page - Features
    'why_choose': 'پرورش میں شراکت دار کیوں منتخب کریں؟',
    'comprehensive_support': 'ہر مرحلے پر آپ کے خاندان کی خوشحالی میں مدد کے لیے جامع حمایت۔',
    'strengthen_relationships': 'تعلقات مضبوط کریں',
    'strengthen_desc': 'ثبوت پر مبنی پرورش کی حکمت عملی کے ذریعے اپنے بچوں کے ساتھ مضبوط تر رشتہ بنائیں۔',
    'expert_guidance': 'ماہر رہنمائی',
    'expert_desc': 'بچوں کی نشوونما کے ماہرین سے پیشہ ورانہ مشورے اور عملی ٹولز حاصل کریں۔',
    'learn_at_pace': 'اپنی رفتار سے سیکھیں',
    'learn_desc': 'خود سے رفتار والے ماڈیولز جو آپ کے مصروف پرورش کے شیڈول میں فٹ ہوتے ہیں۔',
    'proven_methods': 'ثابت شدہ طریقے',
    'proven_desc': 'تحقیق کی حمایت یافتہ تکنیکیں جو آپ کے خاندان کی خوشحالی میں مدد کرتی ہیں۔',
    
    // Home page - How it works
    'how_it_works': 'یہ کیسے کام کرتا ہے',
    'simple_steps': 'اپنے پرورش کے سفر کو تبدیل کرنے کے لیے سادہ مراحل۔',
    'step1_title': 'جائزے مکمل کریں',
    'step1_desc': 'اپنی طاقتوں اور ترقی کے شعبوں کو سمجھنے کے لیے ہمارے جامع پرورش کے جائزے لیں۔',
    'step2_title': 'ماڈیولز تک رسائی حاصل کریں',
    'step2_desc': 'خاص طور پر آپ کے خاندان کی ضروریات کے لیے ڈیزائن کردہ ذاتی نوعیت کے سیکھنے والے ماڈیولز دریافت کریں۔',
    'step3_title': 'خاندانی زندگی کو تبدیل کریں',
    'step3_desc': 'ثابت شدہ حکمت عملی لاغو کریں اور اپنے خاندانی تعلقات کو پھلتے ہوئے دیکھیں۔',
    
    // Home page - Benefits
    'what_you_gain': 'آپ کو کیا حاصل ہوگا',
    'program_provides': 'ہمارا پروگرام آپ کو ایک پرورش کرنے والے خاندانی ماحول بنانے کے لیے عملی ٹولز اور علم فراہم کرتا ہے۔',
    'benefit1': 'اپنے بچوں کے ساتھ بہتر مواصلت',
    'benefit2': 'مؤثر نظم و ضبط کی حکمت عملی',
    'benefit3': 'دباؤ کے انتظام کی تکنیکیں',
    'benefit4': 'بچوں کی نشوونما کی بہتر سمجھ',
    'benefit5': 'مضبوط خاندانی بندھن',
    'benefit6': 'اپنے پرورش کے فیصلوں میں اعتماد',
    'core_assessments': 'بنیادی جائزے',
    'learning_modules': 'سیکھنے والے ماڈیولز',
    'resource_access': 'وسائل تک رسائی',
    'satisfaction': 'اطمینان',
    
    // Home page - CTA
    'ready_to_transform': 'اپنے پرورش کے سفر کو تبدیل کرنے کے لیے تیار ہیں؟',
    'join_parents': 'ہزاروں والدین سے جڑیں جنہوں نے پہلے ہی ثبوت پر مبنی پرورش کی حکمت عملی کی طاقت دریافت کر لی ہے۔',
    'get_started_free': 'مفت میں شروع کریں',
    'learn_more': 'مزید جانیں',
    
    // Footer
    'empowering_families': '2024 سے ثبوت پر مبنی حکمت عملی اور ماہر رہنمائی کے ساتھ خاندانوں کو بااختیار بنانا۔',
    'quick_links': 'فوری لنکس',
    'account': 'اکاؤنٹ',
    'all_rights_reserved': 'جملہ حقوق محفوظ ہیں۔',
    
    // Landing page
    'welcome_back': 'خوش آمدید',
    'my_dashboard': 'میرا ڈیش بورڈ',
    'continue_modules': 'ماڈیولز جاری رکھیں',
    'complete_assessment': 'جائزہ مکمل کریں',
    'welcome_get_started': 'خوش آمدید! آئیں شروع کریں',
    'assessment_desc': 'ماڈیولز تک رسائی سے پہلے، براہ کرم ہمارا ابتدائی جائزہ مکمل کریں تاکہ ہم آپ کو سب سے زیادہ متعلقہ مواد اور حمایت فراہم کر سکیں۔',
    'comprehensive_modules': '10 جامع ماڈیولز',
    'modules_desc': 'تعلقات بنانے سے لے کر فکر کا انتظام کرنے تک، ہر ماڈیول عام پرورش کے چیلنجز کے لیے عملی حکمت عملی فراہم کرتا ہے۔',
    'interactive_activities': 'انٹرایکٹو سرگرمیاں',
    'activities_desc': 'سیکھنے کو مضبوط کرنے کے لیے ڈیزائن کردہ کوئز، تدبر کرنے کی مشقیں اور عملی سرگرمیوں میں شامل ہوں۔',
    'personalized_support': 'ذاتی نوعیت کی حمایت',
    'support_desc': 'ہمارے جائزہ کے ٹولز مواد کو آپ کی مخصوص خاندانی ضروریات اور چیلنجز کے مطابق بنانے میں مدد کرتے ہیں۔',
    'available_modules': 'دستیاب ماڈیولز',
    'program_desc': 'خاندانوں کی خوشحالی میں مدد کے لیے ڈیزائن کردہ ایک جامع پرورش کی حمایتی پروگرام۔',
    
    // Dashboard
    'user_dashboard': 'صارف کا ڈیش بورڈ',
    'overview': 'جائزہ',
    'my_scales': 'میرے پیمانے',
    'module_progress': 'ماڈیول کا پیش رفت',
    'scales_completed': 'مکمل شدہ پیمانے',
    'modules_completed': 'مکمل شدہ ماڈیولز',
    'average_score': 'اوسط اسکور',
    'time_spent': 'صرف کیا گیا وقت',
    'redo_assessment': 'جائزہ دوبارہ کریں',
    'view_modules': 'ماڈیولز دیکھیں',
    'no_modules': 'کوئی ماڈیولز دستیاب نہیں',
    'recent_scale_results': 'حالیہ پیمانے کے نتائج',
    'score': 'اسکور',
    'no_scales_completed': 'ابھی تک کوئی پیمانے مکمل نہیں ہوئے',
    'complete_percent': 'مکمل',
    'no_modules_enrolled': 'ابھی تک کوئی ماڈیولز میں اندراج نہیں ہوا',
    'quick_actions': 'فوری اعمال',
    'review_scales': 'پیمانے کا جائزہ لیں',
    'view_assessments': 'جائزے دیکھیں',
    'continue_learning': 'سیکھنا جاری رکھیں',
    'access_modules': 'ماڈیولز تک رسائی',
    'view_profile': 'پروفائل دیکھیں',
    'manage_account': 'اکاؤنٹ کا انتظام',
    'my_scale_responses': 'میرے پیمانے کے جوابات',
    'scale_name': 'پیمانے کا نام',
    'risk_level': 'خطرے کی سطح',
    'completed_date': 'مکمل تاریخ',
    'time_taken': 'لیا گیا وقت',
    'actions': 'اعمال',
    'redo': 'دوبارہ کریں',
    'no_scale_responses': 'کوئی پیمانے کے جوابات نہیں ملے۔ شروع کرنے کے لیے اپنا پہلا جائزہ مکمل کریں!',
    'my_module_progress': 'میرے ماڈیول کی پیش رفت',
    'module_name': 'ماڈیول کا نام',
    'progress_col': 'پیش رفت',
    'status_col': 'حالت',
    'last_accessed': 'آخری رسائی',
    'action': 'عمل',
    'review': 'جائزہ',
    'continue_btn': 'جاری رکھیں',
    'no_module_enrollments': 'کوئی ماڈیول اندراج نہیں ملے۔ سیکھنا شروع کرنے کے لیے کسی بھی ماڈیول کا صفحہ دیکھیں!',
    'enrolled': 'اندراج شدہ',
    
    // Profile page
    'manage_account_settings': 'اپنی اکاؤنٹ کی ترتیبات کا انتظام کریں اور اپنی پیش رفت دیکھیں',
    'profile_updated': 'پروفائل کامیابی سے اپڈیٹ ہو گیا!',
    'failed_update_profile': 'پروفائل اپڈیٹ کرنے میں ناکام',
    'passwords_not_match': 'نئے پاس ورڈ مماثل نہیں ہیں',
    'password_changed': 'پاس ورڈ کامیابی سے تبدیل ہو گیا!',
    'failed_change_password': 'پاس ورڈ تبدیل کرنے میں ناکام',
    'personal_information': 'ذاتی معلومات',
    'saving': 'محفوظ ہو رہا ہے...',
    'full_name': 'پورا نام',
    'phone': 'فون',
    'location': 'مقام',
    'member_since': 'رکن جب سے',
    'bio': 'تعارف',
    'phone_placeholder': '+1 (555) 000-0000',
    'bio_placeholder': 'اپنے بارے میں ہمیں بتائیں...',
    'not_provided': 'فراہم نہیں کیا گیا',
    'no_bio': 'ابھی تک کوئی تعارف فراہم نہیں کیا گیا۔',
    'security': 'سیکیورٹی',
    'change_password_desc': 'اپنا اکاؤنٹ پاس ورڈ تبدیل کریں',
    'change': 'تبدیل کریں',
    'view_dashboard': 'ڈیش بورڈ دیکھیں',
    'my_assessments': 'میرے جائزے',
    'your_progress': 'آپ کی پیش رفت',
    'modules_done': 'مکمل شدہ ماڈیولز',
    'avg_score': 'اوسط اسکور',
    'current_password': 'موجودہ پاس ورڈ',
    'new_password': 'نیا پاس ورڈ',
    'confirm_new_password': 'نئے پاس ورڈ کی تصدیق کریں',
    'changing': 'تبدیل ہو رہا ہے...',
    
    // Auth pages
    'sign_in_to_account': 'اپنے اکاؤنٹ میں سائن ان کریں',
    'create_new_account': 'نیا اکاؤنٹ بنائیں',
    'enter_email': 'اپنا ای میل درج کریں',
    'enter_password': 'اپنا پاس ورڈ درج کریں',
    'signing_in': 'سائن ان ہو رہا ہے...',
    'sign_in_btn': 'سائن ان کریں',
    'login_failed': 'لاگ ان ناکام۔ براہ کرم دوبارہ کوشش کریں۔',
    'create_your_account': 'اپنا اکاؤنٹ بنائیں',
    'sign_in_existing': 'اپنے موجودہ اکاؤنٹ میں سائن ان کریں',
    'enter_full_name': 'اپنا پورا نام درج کریں',
    'confirm_password': 'پاس ورڈ کی تصدیق کریں',
    'passwords_not_match_auth': 'پاس ورڈ مماثل نہیں ہیں',
    'password_min_chars': 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے',
    'creating_account': 'اکاؤنٹ بنا رہا ہے...',
    'create_account_btn': 'اکاؤنٹ بنائیں',
    'registration_failed': 'رجسٹریشن ناکام۔ براہ کرم دوبارہ کوشش کریں۔',
    
    // Contact page
    'contact_hero_desc': 'ہم آپ سے سننا پسند کریں گے۔ کسی بھی سوال یا حمایت کے لیے ہماری ٹیم سے رابطہ کریں۔',
    'office': 'دفتر',
    'working_hours': 'کام کے اوقات',
    'mon_fri_hours': 'پیر سے جمعہ صبح 8 بجے سے شام 5 بجے تک',
    'respond_24h': 'ہم 24 گھنٹوں کے اندر جواب دیتے ہیں',
    'send_message': 'ہمیں پیغام بھیجیں',
    'your_name': 'آپ کا نام',
    'email_address': 'ای میل ایڈریس',
    'subject': 'موضوع',
    'select_subject': 'موضوع منتخب کریں',
    'general_inquiry': 'عام درخواست',
    'technical_support': 'تکنیکی حمایت',
    'billing_question': 'بلنگ کا سوال',
    'feedback': 'رائے',
    'other': 'دیگر',
    'message': 'پیغام',
    'how_can_help': 'ہم آپ کی کیسے مدد کر سکتے ہیں؟',
    'send_message_btn': 'پیغام بھیجیں',
    'message_sent': 'پیغام بھیج دیا گیا!',
    'get_back_24h': 'ہم 24 گھنٹوں کے اندر آپ سے رابطہ کریں گے۔',
    'faq': 'اکثر پوچھے گئے سوالات',
    'still_have_questions': 'ابھی بھی سوالات ہیں؟',
    'support_team_help': 'ہماری حمایتی ٹیم ہمیشہ کسی بھی سوال یا تشویش میں آپ کی مدد کے لیے یہاں ہے۔',
    'email_support_team': 'حمایتی ٹیم کو ای میل کریں',
    'map_coming_soon': 'انٹرایکٹو نقشہ جلد آ رہا ہے',
    'faq_q1': 'میں پروگرام کیسے شروع کروں؟',
    'faq_a1': 'بس ایک اکاؤنٹ بنائیں، ابتدائی جائزے مکمل کریں، اور آپ کو ذاتی نوعیت کے سیکھنے والے ماڈیولز کے ذریعے رہنمائی کی جائے گی۔',
    'faq_q2': 'کیا یہ پروگرام تمام پرورش کے مراحل کے لیے موزوں ہے؟',
    'faq_a2': 'جی ہاں! ہمارا پروگرام تمام عمر کے بچوں والے والدین کی حمایت کے لیے ڈیزائن کیا گیا ہے، شیر خوار بچوں سے لے کر نوعمروں تک۔',
    'faq_q3': 'کیا میں موبائل ڈیوائسز پر پروگرام تک رسائی حاصل کر سکتا ہوں؟',
    'faq_a3': 'بالکل! ہمارا پلیٹ فارم مکمل طور پر رسپانسو ہے اور اسمارٹ فونز، ٹیبلٹس اور کمپیوٹرز پر بغیر کسی رکاوٹ کے کام کرتا ہے۔',
    'faq_q4': 'اگر مجھے اضافی حمایت کی ضرورت ہو تو؟',
    'faq_a4': 'ہم ای میل سپورٹ، کمیونٹی فورمز، اور اختیاری ایک پر ایک مشاورت سمیت مختلف سپورٹ چینلز پیش کرتے ہیں۔',
    
    // Scales
    'scale_child_mental_health': 'بچوں کی دماغی صحت کا پیمانہ',
    'scale_parent_child_relationship': 'والدین-بچہ تعلقات کا پیمانہ',
    'scale_parental_mental_wellbeing': 'والدین کی دماغی خوشحالی کا پیمانہ',
    'scale_parental_self_efficacy': 'والدین کی خودکارکردگی کا پیمانہ',
    'question': 'سوال',
    'of': 'میں سے',
    'next': 'اگلا',
    'previous': 'پچھلا',
    'submit': 'جمع کرائیں',
    'retake': 'دوبارہ لیں',
    'your_score': 'آپ کا اسکور',
    'completed': 'مکمل',
    'in_progress': 'جاری ہے',
    'not_started': 'شروع نہیں ہوا',
    
    // Common
    'loading': 'لوڈ ہو رہا ہے...',
    'error': 'خرابی',
    'success': 'کامیابی',
    'cancel': 'منسوخ کریں',
    'save': 'محفوظ کریں',
    'edit': 'ترمیم کریں',
    'delete': 'حذف کریں',
    'confirm': 'تصدیق کریں',
    'close': 'بند کریں',
    'back': 'واپس',
    'continue': 'جاری رکھیں',
    'welcome': 'خوش آمدید',
    'supporting_families': 'خاندانوں کی حمایت میں',
    'progress': 'پیش رفت',
    'completed_percent': 'مکمل',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language')
    return (saved as Language) || 'en'
  })

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
    // Force reload to ensure all components re-render with new language
    window.location.reload()
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
